"""
This module identifies personnel strings that have uncommon personnel within
them and parses them accordingly.
"""
common_oddities = ['unidentified orchestra',
                   'unidentified orchestra, including strings',
                   'unidentified orchestra and vocal group',
                   'unidentified big band, including strings',
                   'unidentified brass, reeds and vocals'
                   'unidentified strings and vocals',
                   'unidentified strings and chorus',
                   'unidentified strings',
                   'with unidentified vocal group and orchestra',
                   '+ overdubs: unidentified strings',
                   'unidentified large orchestra',
                   'New York Philharmonic',
                   'Cincinnati Symphony Orchestra',
                   'The Montreal International Jazz Festival Orchestra',
                   'Cathedral Choral Society Chorus, Duke Ellington School Of Arts Show Choir, Cathedral Choral Society Orchestra',
                   'unidentified chorus',
                   'unidentified vocal chorus',
                   'unidentified brass, reeds, rhythm and strings',
                   'unidentified large studio band',
                   'with unidentified woodwind quintet: unknown',
                   'Sydney Symphony Orchestra',
                   'unidentified brass and strings',
                   'unidentified horns and strings',
                   'Onzy Matthews Orchestra',
                   'unidentified large orchestra, strings and choir',
                   'unidentified brass, woodwinds, rhythm and strings',
                   'unidentified brass, woodwinds and strings',
                   'unidentified horns, reeds and strings',
                   'unidentified studio band',
                   'unidentified woodwinds',
                   'percussion and choir',
                   'unidentified brass, percussion and choir',
                   'unidentified brass, strings and chorus',
                   'unidentified orchestra and choir',
                   'unidentified strings, and others',
                   'unidentified trombones, guitar, woodwinds, harp and strings',
                   'unidentified vocal group',
                   'unidentified large symphony orchestra',
                   'String Section Of The Sudfunk Symphony Orchestra, Stuttgart',
                   'Strings Of Sudfunk Symphony Orchestra, Stuttgart',
                   'Members Of Radio Symphony Orchestra, Stuttgart',
                   'unidentified string quartet',
                   '+ overdubs: unidentified horns and strings',
                   'unidentified woodwinds and strings',
                   'unidentified brass and woodwinds',
                   'unidentified horn and brass',
                   'unidentified choir',
                   'unidentified orchestra, and others',
                   'London Orchestra, The Royal Ballet, The Cambodian Royal Palace',
                   'with a full orchestra:',
                   'unidentified band vocals (-1)',
                   'unidentified 5 strings',
                   'unidentified oboe and strings',
                   'unidentified Afro-Cuban band',
                   'unidentified big band',
                   'unidentified 22 voices',
                   'with unidentified brass, woodwinds, strings and vocal chorus',
                   'unidentified percussion',
                   'unidentified studio orchestra',
                   'unidentified voices',
                   'unidentified strings, harp, vocal choir'
]

# Ideas:
#    - search common terms, also 'orchestra' and 'unidentified'
#    - can I break these strings down into their smallest common components and search by those?
#    - for long groups of instruments I could look for the 'and' keyword?
